### ISSUE TITLE
Feature request: Add ability to export loot tables

### ISSUE THREAD

**Issue by BakermanLP** [PearXTeam/pmdumper#1]
Hello,

this is just a feature request.

It would be nice to export all the loot tables. 

Thanks for listening

Michael (aka BakermanLP)

**Comment by mrapplexz** [comment]
I'm working on it.

**Comment by BakermanLP** [comment]
Cool. Thank you

Maxim notifications@github.com schrieb am Do., 10. Nov. 2016, 17:09:

**Comment by mrapplexz** [comment]
I'm rewriting the mod now and this feature will be implemented in PM Dumper 2.0.0.
