### ISSUE TITLE
Feature: Dump in csv format or without formatting

### ISSUE THREAD

**Issue by NHDriver4** [PearXTeam/pmdumper#2]
The table output, while it looks nice, is not friendly when trying to work with massive amounts of items. It would be nice if there was an option or command flag that dumped items in csv format. Even if a 2nd file was created without additional input, that would be useful.

**Comment by mrapplexz** [comment]
I'm very busy at this moment :(. I do it when I've get some free time.

**Comment by mrapplexz** [comment]
Nope, I do this today :D. It just requires 20-30 lines of code.

**Comment by mrapplexz** [comment]
Implemented in 1.4.0.
