### ISSUE TITLE
Feature Request: Mapping Assets 

### ISSUE THREAD

**Issue by sfxworks** [PearXTeam/pmdumper#7]
I would like to have a path to assets within the jar that corresponds to their referenced items. Please also include modded items/objects with 3d models.

**Comment by mrapplexz** [comment]
Hello. Sorry for a long response :sweat_smile:.
`a path to assets within the jar that corresponds to their referenced items`
Can you give an example?

**Comment by sfxworks** [comment]
Super bad example that shouldn't be taken literally since I don't know class names:

minecraft.pickacke.iron
>assets/minecraft/img/pickaxe/iron.png

Mainly for mods though. I want the paths to 3d .obj and texture files so I can get them from mods and display them on the web.

**Comment by mrapplexz** [comment]
So, I've included model resource locations (e.g., `minecraft:diamond_pickaxe#inventory` for `minecraft:diamond_pickaxe`) to the items dumper and texture paths (e.g., `assets/minecraft/textures/items/diamond_pickaxe.png` for `minecraft:diamond_pickaxe#inventory`) to the models dumper, but dumping models' paths or models itself is complicated and probably won't be added in PMDumper 3.0.
![image](https://user-images.githubusercontent.com/7630912/49688569-07a72380-fb36-11e8-9705-537cd0e4913b.png)
![image](https://user-images.githubusercontent.com/7630912/49688548-c3b41e80-fb35-11e8-88fa-405373c1d25d.png)

**Comment by sfxworks** [comment]
Any idea when? It would be put to great use.

**Comment by mrapplexz** [comment]
I've found a temporary solution after some research. As it turned out, paths to the originating models of some baked models can be obtained using a bit of dirty hacks (see 39abb8611f8bfffdbf04a99ba94c0b670a4e00bd).
![image](https://user-images.githubusercontent.com/7630912/49781849-07757680-fd36-11e8-9a05-8c9ac1266e5c.png)

**Comment by sfxworks** [comment]
Gracias! I'll update you on my work later on :D
