### ISSUE TITLE
Request - Fluid Buckets List 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PearXTeam/pmdumper#9]
So I need the correct name of fluid buckets so I can add stack size changes using upsizer mod

**Comment by mrapplexz** [comment]
You can acquire IDs and NBT tags of fluid buckets by using the ItemStacks dumper: `/pmdumper itemstacks csv`.
![image](https://user-images.githubusercontent.com/7630912/52123505-26aec700-2648-11e9-91d0-4eb835cc1b29.png)

**Comment by P3rf3ctXZer0** [comment]
Sorry I forgot to close this issue. I figured it out. Thank you though.
